DefaultContentLanguage = "en"
RemovePathAccents = true
baseURL = "https://megapiksel.id/"
canonifyURLs = true
enableRobotsTXT = true
languageCode = "en"
paginate = 9
theme = "less"
timeout = 200000
[author]
name = "Jaka"
[imaging]
resampleFilter = "lanczos"
[[menu.main]]
identifier = "infos"
name = "About"
title = "Infos & Contact"
url = "/infos"
weight = 4
[[menu.main]]
identifier = "guides"
name = "Tips & Gear"
title = "Tips & Gear"
url = "/guides/"
weight = 3
[[menu.main]]
identifier = "aventures"
name = "Aventures"
title = "Aventures"
url = "/aventures/"
weight = 2
[[menu.main]]
identifier = "journal"
name = "Journal"
title = "Journal"
url = "/journal/"
weight = 1
[params]
accentColor = "#019CB5"
bodyFont = "Lato"
hasLogo = true
sansSerifFont = "Josefin Sans"
sizes = ["2048", "1024", "512"]
tags = []
titleFont = "Josefin Sans"
[params.social]
anchor = "megapiksel"
domain = "megapiksel.id"
email = "jaka@megapiksel.com"
instagram = "megapiksel.id"
twitter = "megapiksel_id"
youtube = "UC6z4Yl7eHnpq70sytIR1ljg"
[params.titles]
categories = "Catégories"
posts = "Journal"
[permalinks]
categories = "/:slug"
posts = "/:slug"
[[related.indices]]
includeNewer = true
name = "categories"
weight = 1
[taxonomies]
category = "categories"
